// Throwaway generator for the S4 spike: produces 30 fake "block" modules
// and one synthetic "wires" file that type-checks the wiring between them.
//
// Run with: bun run generate.ts
import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";

const BLOCKS_DIR = join(import.meta.dir, "blocks");
mkdirSync(BLOCKS_DIR, { recursive: true });

const NUM_BLOCKS = 30;
const FAMILY_SIZE = 6; // 30 / 5 families

type Family = "A" | "B" | "C" | "D" | "E";

function familyOf(i: number): Family {
  const idx = Math.floor(i / FAMILY_SIZE);
  return (["A", "B", "C", "D", "E"] as const)[idx]!;
}

function pad(i: number): string {
  return i.toString().padStart(2, "0");
}

// Each family gets a distinct Inputs/Outputs shape so the 30 blocks aren't
// literal copy-paste of each other.
function blockSource(i: number): string {
  const fam = familyOf(i);
  const name = `block${pad(i)}`;

  switch (fam) {
    case "A":
      // plain numeric value + timestamp (timestamp passed through so
      // out1 -> in1 chains stay assignable)
      return `// ${name}: numeric value + timestamp block
export interface Inputs {
  in1: { value: number; at: number };
}
export interface Outputs {
  out1: { value: number; at: number };
}
export async function process(inputs: Inputs): Promise<Outputs> {
  return { out1: { value: inputs.in1.value, at: inputs.in1.at } };
}
`;
    case "B":
      // string payload (timestamp passed through, same reasoning as family A)
      return `// ${name}: string payload block
export interface Inputs {
  in1: { text: string; at: number };
}
export interface Outputs {
  out1: { text: string; at: number };
}
export async function process(inputs: Inputs): Promise<Outputs> {
  return { out1: { text: inputs.in1.text.trim(), at: inputs.in1.at } };
}
`;
    case "C":
      // nested object with metadata
      return `// ${name}: nested-object value-with-metadata block
export interface Inputs {
  in1: { value: number; meta: { unit: string } };
}
export interface Outputs {
  out1: { value: number; meta: { unit: string } };
}
export async function process(inputs: Inputs): Promise<Outputs> {
  return { out1: { value: inputs.in1.value * 2, meta: inputs.in1.meta } };
}
`;
    case "D":
      // array payload
      return `// ${name}: numeric array block
export interface Inputs {
  in1: { items: number[] };
}
export interface Outputs {
  out1: { items: number[] };
}
export async function process(inputs: Inputs): Promise<Outputs> {
  return { out1: { items: inputs.in1.items.slice().reverse() } };
}
`;
    case "E":
      // boolean flag + numeric value
      return `// ${name}: flagged-value block
export interface Inputs {
  in1: { flag: boolean; value: number };
}
export interface Outputs {
  out1: { flag: boolean; value: number };
}
export async function process(inputs: Inputs): Promise<Outputs> {
  return { out1: { flag: !inputs.in1.flag, value: inputs.in1.value } };
}
`;
  }
}

for (let i = 0; i < NUM_BLOCKS; i++) {
  writeFileSync(join(BLOCKS_DIR, `block${pad(i)}.ts`), blockSource(i), "utf8");
}

// ---------------------------------------------------------------------------
// Build the wire graph: linear chains within each family (0-5, 6-11, ...)
// plus a handful of extra fork/join wires so it's not purely linear.
// ---------------------------------------------------------------------------
type Wire = { src: number; dst: number };
const wires: Wire[] = [];

for (let fam = 0; fam < 5; fam++) {
  const base = fam * FAMILY_SIZE;
  for (let k = 0; k < FAMILY_SIZE - 1; k++) {
    wires.push({ src: base + k, dst: base + k + 1 });
  }
}

// Extra fork/join wires (still within a family so types line up structurally):
wires.push({ src: 0, dst: 2 }); // fork: block00 also feeds block02 directly
wires.push({ src: 7, dst: 9 }); // join: block07 -> block09 (in addition to 8 -> 9)
wires.push({ src: 13, dst: 15 }); // fork: block13 also feeds block15 directly
wires.push({ src: 19, dst: 21 }); // join: block19 -> block21 (in addition to 20 -> 21)
wires.push({ src: 25, dst: 27 }); // fork: block25 also feeds block27 directly

const imports = Array.from({ length: NUM_BLOCKS }, (_, i) => {
  const n = pad(i);
  return `import type { Inputs as Inputs${n}, Outputs as Outputs${n} } from "./blocks/block${n}";`;
}).join("\n");

const wireChecks = wires
  .map((w, idx) => {
    const s = pad(w.src);
    const d = pad(w.dst);
    return `// wire: block${s}.out1 -> block${d}.in1
type Wire${idx.toString().padStart(2, "0")} = AssertAssignable<Inputs${d}["in1"], Outputs${s}["out1"]>;`;
  })
  .join("\n");

const wiresSource = `// AUTO-GENERATED by generate.ts — do not hand-edit.
// Synthetic "flow" file: imports every real block module and type-checks
// that each wire's source-output type is assignable to the destination
// input type it's connected to. If this file fails to type-check, tsc
// will report an error at the specific wire that's broken.

${imports}

// AssertAssignable<Dest, Src> only type-checks if Src is assignable to Dest.
// If a wire's source output type doesn't satisfy the destination input
// type, TypeScript reports "does not satisfy the constraint" right here.
type AssertAssignable<Dest, Src extends Dest> = true;

${wireChecks}

// Keep a value reference so nothing here is considered unused by tooling.
export const wireCount = ${wires.length};
`;

writeFileSync(join(import.meta.dir, "wires.ts"), wiresSource, "utf8");

console.log(`Generated ${NUM_BLOCKS} blocks and ${wires.length} wires.`);
