// AUTO-GENERATED by generate.ts — do not hand-edit.
// Synthetic "flow" file: imports every real block module and type-checks
// that each wire's source-output type is assignable to the destination
// input type it's connected to. If this file fails to type-check, tsc
// will report an error at the specific wire that's broken.

import type { Inputs as Inputs00, Outputs as Outputs00 } from "./blocks/block00";
import type { Inputs as Inputs01, Outputs as Outputs01 } from "./blocks/block01";
import type { Inputs as Inputs02, Outputs as Outputs02 } from "./blocks/block02";
import type { Inputs as Inputs03, Outputs as Outputs03 } from "./blocks/block03";
import type { Inputs as Inputs04, Outputs as Outputs04 } from "./blocks/block04";
import type { Inputs as Inputs05, Outputs as Outputs05 } from "./blocks/block05";
import type { Inputs as Inputs06, Outputs as Outputs06 } from "./blocks/block06";
import type { Inputs as Inputs07, Outputs as Outputs07 } from "./blocks/block07";
import type { Inputs as Inputs08, Outputs as Outputs08 } from "./blocks/block08";
import type { Inputs as Inputs09, Outputs as Outputs09 } from "./blocks/block09";
import type { Inputs as Inputs10, Outputs as Outputs10 } from "./blocks/block10";
import type { Inputs as Inputs11, Outputs as Outputs11 } from "./blocks/block11";
import type { Inputs as Inputs12, Outputs as Outputs12 } from "./blocks/block12";
import type { Inputs as Inputs13, Outputs as Outputs13 } from "./blocks/block13";
import type { Inputs as Inputs14, Outputs as Outputs14 } from "./blocks/block14";
import type { Inputs as Inputs15, Outputs as Outputs15 } from "./blocks/block15";
import type { Inputs as Inputs16, Outputs as Outputs16 } from "./blocks/block16";
import type { Inputs as Inputs17, Outputs as Outputs17 } from "./blocks/block17";
import type { Inputs as Inputs18, Outputs as Outputs18 } from "./blocks/block18";
import type { Inputs as Inputs19, Outputs as Outputs19 } from "./blocks/block19";
import type { Inputs as Inputs20, Outputs as Outputs20 } from "./blocks/block20";
import type { Inputs as Inputs21, Outputs as Outputs21 } from "./blocks/block21";
import type { Inputs as Inputs22, Outputs as Outputs22 } from "./blocks/block22";
import type { Inputs as Inputs23, Outputs as Outputs23 } from "./blocks/block23";
import type { Inputs as Inputs24, Outputs as Outputs24 } from "./blocks/block24";
import type { Inputs as Inputs25, Outputs as Outputs25 } from "./blocks/block25";
import type { Inputs as Inputs26, Outputs as Outputs26 } from "./blocks/block26";
import type { Inputs as Inputs27, Outputs as Outputs27 } from "./blocks/block27";
import type { Inputs as Inputs28, Outputs as Outputs28 } from "./blocks/block28";
import type { Inputs as Inputs29, Outputs as Outputs29 } from "./blocks/block29";

// AssertAssignable<Dest, Src> only type-checks if Src is assignable to Dest.
// If a wire's source output type doesn't satisfy the destination input
// type, TypeScript reports "does not satisfy the constraint" right here.
type AssertAssignable<Dest, Src extends Dest> = true;

// wire: block00.out1 -> block01.in1
type Wire00 = AssertAssignable<Inputs01["in1"], Outputs00["out1"]>;
// wire: block01.out1 -> block02.in1
type Wire01 = AssertAssignable<Inputs02["in1"], Outputs01["out1"]>;
// wire: block02.out1 -> block03.in1
type Wire02 = AssertAssignable<Inputs03["in1"], Outputs02["out1"]>;
// wire: block03.out1 -> block04.in1
type Wire03 = AssertAssignable<Inputs04["in1"], Outputs03["out1"]>;
// wire: block04.out1 -> block05.in1
type Wire04 = AssertAssignable<Inputs05["in1"], Outputs04["out1"]>;
// wire: block06.out1 -> block07.in1
type Wire05 = AssertAssignable<Inputs07["in1"], Outputs06["out1"]>;
// wire: block07.out1 -> block08.in1
type Wire06 = AssertAssignable<Inputs08["in1"], Outputs07["out1"]>;
// wire: block08.out1 -> block09.in1
type Wire07 = AssertAssignable<Inputs09["in1"], Outputs08["out1"]>;
// wire: block09.out1 -> block10.in1
type Wire08 = AssertAssignable<Inputs10["in1"], Outputs09["out1"]>;
// wire: block10.out1 -> block11.in1
type Wire09 = AssertAssignable<Inputs11["in1"], Outputs10["out1"]>;
// wire: block12.out1 -> block13.in1
type Wire10 = AssertAssignable<Inputs13["in1"], Outputs12["out1"]>;
// wire: block13.out1 -> block14.in1
type Wire11 = AssertAssignable<Inputs14["in1"], Outputs13["out1"]>;
// wire: block14.out1 -> block15.in1
type Wire12 = AssertAssignable<Inputs15["in1"], Outputs14["out1"]>;
// wire: block15.out1 -> block16.in1
type Wire13 = AssertAssignable<Inputs16["in1"], Outputs15["out1"]>;
// wire: block16.out1 -> block17.in1
type Wire14 = AssertAssignable<Inputs17["in1"], Outputs16["out1"]>;
// wire: block18.out1 -> block19.in1
type Wire15 = AssertAssignable<Inputs19["in1"], Outputs18["out1"]>;
// wire: block19.out1 -> block20.in1
type Wire16 = AssertAssignable<Inputs20["in1"], Outputs19["out1"]>;
// wire: block20.out1 -> block21.in1
type Wire17 = AssertAssignable<Inputs21["in1"], Outputs20["out1"]>;
// wire: block21.out1 -> block22.in1
type Wire18 = AssertAssignable<Inputs22["in1"], Outputs21["out1"]>;
// wire: block22.out1 -> block23.in1
type Wire19 = AssertAssignable<Inputs23["in1"], Outputs22["out1"]>;
// wire: block24.out1 -> block25.in1
type Wire20 = AssertAssignable<Inputs25["in1"], Outputs24["out1"]>;
// wire: block25.out1 -> block26.in1
type Wire21 = AssertAssignable<Inputs26["in1"], Outputs25["out1"]>;
// wire: block26.out1 -> block27.in1
type Wire22 = AssertAssignable<Inputs27["in1"], Outputs26["out1"]>;
// wire: block27.out1 -> block28.in1
type Wire23 = AssertAssignable<Inputs28["in1"], Outputs27["out1"]>;
// wire: block28.out1 -> block29.in1
type Wire24 = AssertAssignable<Inputs29["in1"], Outputs28["out1"]>;
// wire: block00.out1 -> block02.in1
type Wire25 = AssertAssignable<Inputs02["in1"], Outputs00["out1"]>;
// wire: block07.out1 -> block09.in1
type Wire26 = AssertAssignable<Inputs09["in1"], Outputs07["out1"]>;
// wire: block13.out1 -> block15.in1
type Wire27 = AssertAssignable<Inputs15["in1"], Outputs13["out1"]>;
// wire: block19.out1 -> block21.in1
type Wire28 = AssertAssignable<Inputs21["in1"], Outputs19["out1"]>;
// wire: block25.out1 -> block27.in1
type Wire29 = AssertAssignable<Inputs27["in1"], Outputs25["out1"]>;

// Keep a value reference so nothing here is considered unused by tooling.
export const wireCount = 30;
