import type { LoadedFlow } from "../router/types";

/**
 * Generates a synthetic TypeScript file that imports every real block module
 * used across the given flows and asserts each wire's source-output type is
 * assignable to its destination-input type. Pattern proven in
 * spikes/s4-typecheck-latency: `type AssertAssignable<Dest, Src extends Dest> = true`
 * fails to compile at the exact wire whose types don't line up.
 */
export function generateWireAssertions(flows: LoadedFlow[]): string {
  const importLines: string[] = [];
  const assertLines: string[] = [];
  const ident = new Map<string, string>(); // `${flowName}::${nodeId}` -> local identifier
  let n = 0;
  let w = 0;

  for (const flow of flows) {
    for (const [nodeId, node] of flow.nodes) {
      const id = `N${n++}`;
      ident.set(`${flow.name}::${nodeId}`, id);
      // Plain (not `import type`) on purpose: each Nn is used in a `typeof`
      // type position below, which needs a real value binding, not a
      // type-only one — `import type` bindings can't be fed to `typeof`.
      importLines.push(
        `import ${id} from ${JSON.stringify(node.blockSpecifier)};`,
      );
    }
  }

  for (const flow of flows) {
    for (const [srcKey, destinations] of flow.wireIndex) {
      const [srcNodeId, srcPort] = srcKey.split(".") as [string, string];
      const src = ident.get(`${flow.name}::${srcNodeId}`);
      for (const dest of destinations) {
        const dst = ident.get(`${flow.name}::${dest.nodeId}`);
        assertLines.push(
          `// ${flow.name}: ${srcNodeId}.${srcPort} -> ${dest.nodeId}.${dest.port}`,
          `type W${w++} = AssertAssignable<InputsOf<typeof ${dst}>[${JSON.stringify(dest.port)}], OutputsOf<typeof ${src}>[${JSON.stringify(srcPort)}]>;`,
        );
      }
    }
  }

  return `${[
    "// AUTO-GENERATED by flowbun's typecheck generator — do not hand-edit.",
    'import type { InputsOf, OutputsOf } from "flowbun";',
    ...importLines,
    "",
    "type AssertAssignable<Dest, Src extends Dest> = true;",
    "",
    ...assertLines,
    "",
    `export const wireCount = ${w};`,
  ].join("\n")}\n`;
}
