import type { LoadedFlow } from "../router/types";

/**
 * Generates a synthetic TypeScript file that imports every real block module
 * used across the given flows and asserts (a) each wire's source-output type
 * is assignable to its destination-input type, and (b) each node's resolved
 * config (defaults merged with whatever the wiring file overrode — the same
 * merge assembleFlow already did) is assignable to its block's declared
 * Config type. Pattern proven in spikes/s4-typecheck-latency:
 * `type AssertAssignable<Dest, Src extends Dest> = true` fails to compile at
 * the exact wire (or, here, the exact config) whose types don't line up.
 *
 * The config check is emitted as `const _cfg_Nn: Partial<typeof Nn.config> =
 * <the actual merged config, as a literal>` — TypeScript's excess-property
 * checking on object literals assigned directly to a typed position is what
 * catches a typo'd key or a wrong-typed value; a config object built up
 * some other way (spread, a variable) wouldn't trigger it. This was
 * previously the one gap in the "two-tier trust" story: the wire gate
 * checked port types but nothing checked node config against the block's
 * own declared shape, so a typo'd or wrong-typed config field passed
 * straight through to a running block silently defaulted.
 */
export function generateWireAssertions(flows: LoadedFlow[]): string {
  const importLines: string[] = [];
  const assertLines: string[] = [];
  const configLines: string[] = [];
  const ident = new Map<string, string>(); // `${flowName}::${nodeId}` -> local identifier
  let n = 0;
  let w = 0;

  for (const flow of flows) {
    for (const [nodeId, node] of flow.nodes) {
      const id = `N${n++}`;
      ident.set(`${flow.name}::${nodeId}`, id);
      // Plain (not `import type`) on purpose: each Nn is used in a `typeof`
      // type position below, which needs a real value binding, not a
      // type-only one — `import type` bindings can't be fed to `typeof`.
      importLines.push(
        `import ${id} from ${JSON.stringify(node.blockSpecifier)};`,
      );
      configLines.push(
        `// ${flow.name}: ${nodeId} config`,
        `const _cfg_${id}: Partial<typeof ${id}.config> = ${JSON.stringify(node.config)};`,
      );
    }
  }

  for (const flow of flows) {
    for (const [srcKey, destinations] of flow.wireIndex) {
      const [srcNodeId, srcPort] = srcKey.split(".") as [string, string];
      const src = ident.get(`${flow.name}::${srcNodeId}`);
      for (const dest of destinations) {
        const dst = ident.get(`${flow.name}::${dest.nodeId}`);
        assertLines.push(
          `// ${flow.name}: ${srcNodeId}.${srcPort} -> ${dest.nodeId}.${dest.port}`,
          `type W${w++} = AssertAssignable<InputsOf<typeof ${dst}>[${JSON.stringify(dest.port)}], OutputsOf<typeof ${src}>[${JSON.stringify(srcPort)}]>;`,
        );
      }
    }
  }

  return `${[
    "// AUTO-GENERATED by flowbun's typecheck generator — do not hand-edit.",
    "// biome-ignore-all lint/correctness/noUnusedVariables: _cfg_* bindings exist only to trigger excess-property checking, see the module doc comment.",
    'import type { InputsOf, OutputsOf } from "flowbun";',
    ...importLines,
    "",
    "type AssertAssignable<Dest, Src extends Dest> = true;",
    "",
    ...configLines,
    "",
    ...assertLines,
    "",
    `export const wireCount = ${w};`,
  ].join("\n")}\n`;
}
